spring.application.name=ai-health-assistant

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ai_health_assistant_platform
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configurations
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server Port
server.port=8080